services:
  - name: "Http tester"
    host: "https://httpbin.org"
    port: ""
    endpoint: "/http-test"
  - name: "Dogs"
    host: "https://dog.ceo"
    port: ""
    endpoint: "/dogs"
  - name: "Dummy Data"
    host: "https://dummyjson.com"
    port: ""
    endpoint: "/dummy"

rate-limit:
  rate: 1
  burst: 2